### ISSUE TITLE
Server cannot handle storing all expected barcodes during Start New Plate?

### ISSUE THREAD

**Issue by noor01** [shassathe/covid_qPCR_test#20]
Uploaded 5000 barcodes and then clicked on "Start A New Plate". Got this error:

[10/Apr/2020 05:42:47] "POST /qpcr_records/ HTTP/1.1" 200 24133
_auth_user_id
2
_auth_user_backend
django.contrib.auth.backends.ModelBackend
_auth_user_hash
6535bee3c4d0524022c786941dde608ae3a7452e
ssp_well
X
current_barcodes
[]
expected_barcodes
['Barcode,"Last, First"', '', '00028A,"Ca.......[It lists out all the barcodes].........]
[10/Apr/2020 05:46:26] "GET /qpcr_records/start_sampling_plate/ HTTP/1.1" 200 6524
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55026)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/opt/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/opt/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------

**Comment by noor01** [comment]
It was an issue with the file being uploaded. Closing
