### ISSUE TITLE
`rsp_id` is never set

### ISSUE THREAD

**Issue by ckmah** [shassathe/covid_qPCR_test#39]
Should this just be set to the same ID for `rep_id`? Or do we need to update a form to record this value?
https://github.com/shassathe/covid_qPCR_test/blob/f177bca74855c216fa369a4a1330a5b92547517d/qpcr_records/views.py#L49-L52

> MultiValueDictKeyError at /qpcr_records/
`rsp_id`

```python
Environment:


Request Method: GET
Request URL: http://localhost:8000/qpcr_records/?csrfmiddlewaretoken=V1DjzDqk09lk1JR5Z9j7W12eRo3RNabRaLd0dVsoscawQN8W42OTpCajb0crh5EU&sep_id=234234&rep_id=345345

Django Version: 3.0.3
Python Version: 3.8.1
Installed Applications:
['qpcr_records.apps.QpcrRecordsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crispy_forms',
 'storages',
 'django_tables2']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)

During handling of the above exception ('rsp_id'), another exception occurred:
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/Clarence/Documents/covid_qPCR_test/qpcr_records/views.py", line 51, in index
    rsp_id=request.GET['rsp_id'],
  File "/Users/Clarence/miniconda3/envs/covid_app/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /qpcr_records/
Exception Value: 'rsp_id'
```

**Comment by shassathe** [comment]
The rsp_id is recorded in the next form. Had to move the capture around based on user review. Will be updated in my next push

**Comment by shassathe** [comment]
Check my latest push from today morning #40962.
rsp_id is set on line # 108
Closing
